apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: demo-app
spec:
  template:
    spec:
      containers:
        - name: api-node
          image: dembyvlad/devops-directive-docker-course-api-node:STAGING_VERSION
